# Generated by Django 6.0.4 on 2026-04-21 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=5)),
                ('gradient_from', models.CharField(default='#F5A623', max_length=20)),
                ('gradient_to', models.CharField(default='#E91E8C', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='celebrities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Celebrities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='charities/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Charities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('birthday', 'Birthday'), ('sports', 'Sports'), ('love_story', 'Love Story'), ('charity', 'Charity'), ('general', 'General')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('tag_color', models.CharField(blank=True, max_length=20)),
                ('read_time', models.CharField(blank=True, max_length=20)),
                ('reads', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.celebrity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoveStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('read_time', models.CharField(blank=True, max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('avatar', models.CharField(blank=True, max_length=5)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('tag_color', models.CharField(blank=True, max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
