# Generated by Django 5.2.7 on 2026-04-23 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lovestory',
            name='read_time',
        ),
        migrations.AddField(
            model_name='article',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='articles/audio/'),
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='birthdate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='initials',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='charity',
            name='tag',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='lovestory',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('subscriber', 'author')},
            },
        ),
    ]
