# Generated by Django 5.2.7 on 2026-04-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_article_read_time_remove_celebrity_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lovestory',
            name='author_name',
        ),
        migrations.AddField(
            model_name='lovestory',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lovestory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='love_stories/'),
        ),
        migrations.AddField(
            model_name='lovestory',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
