# Generated by Django 5.2.7 on 2026-04-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lovestory_author_name_lovestory_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charity',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charity',
            name='donors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='charity',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charity',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
