# Generated by Django 5.2.7 on 2026-07-23 08:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lovestorycomment_lovestorylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.celebrant_photo_path)),
                ('birth_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('birth_day', models.PositiveSmallIntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('big_wish', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebration_triggered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['birth_month', 'birth_day'],
            },
        ),
    ]
